# Generated by Django 5.1.5 on 2025-04-07 17:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    (
                        "change_product_is_published",
                        "Может менять статус публикации продукта",
                    ),
                    ("change_product_description", "Может менять описание продукта"),
                    ("change_product_category", "Может менять категорию продукта"),
                ]
            },
        ),
    ]
